version: "3"
services:
  client:
    image: kubrickcode/devprofiler:client
    networks:
      - app-network

  server:
    image: kubrickcode/devprofiler:express
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file: .env.production

networks:
  app-network:
    driver: bridge
